/**
 * prodapi.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIVeripassG1HashSet.h"

namespace OpenAPI
{

/*
 * OpenAPIVeripassG1Claim
 *
 * 
 */
class OPENAPI_API OpenAPIVeripassG1Claim : public Model
{
public:
    virtual ~OpenAPIVeripassG1Claim() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<TMap<FString, OpenAPIVeripassG1HashSet>> Anchors;
	TOptional<int32> Age;
};

}
