/**
 * prodapi.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "CoreMinimal.h"
#include "OpenAPIBaseModel.h"

namespace OpenAPI
{

class OPENAPI_API OpenAPIVPCApi
{
public:
	OpenAPIVPCApi();
	~OpenAPIVPCApi();

	/* Sets the URL Endpoint.
	* Note: several fallback endpoints can be configured in request retry policies, see Request::SetShouldRetry */
	void SetURL(const FString& Url);

	/* Adds global header params to all requests */
	void AddHeaderParam(const FString& Key, const FString& Value);
	void ClearHeaderParams();

	/* Sets the retry manager to the user-defined retry manager. User must manage the lifetime of the retry manager.
	* If no retry manager is specified and a request needs retries, a default retry manager will be used.
	* See also: Request::SetShouldRetry */
	void SetHttpRetryManager(FHttpRetrySystem::FManager& RetryManager);
	FHttpRetrySystem::FManager& GetHttpRetryManager();

	class VPCCreateConsentRequest;
	class VPCCreateConsentResponse;
	class VPCGetConsentRequest;
	class VPCGetConsentResponse;
	class VPCGetConsentZeroRequest;
	class VPCGetConsentZeroResponse;
	
    DECLARE_DELEGATE_OneParam(FVPCCreateConsentDelegate, const VPCCreateConsentResponse&);
    DECLARE_DELEGATE_OneParam(FVPCGetConsentDelegate, const VPCGetConsentResponse&);
    DECLARE_DELEGATE_OneParam(FVPCGetConsentZeroDelegate, const VPCGetConsentZeroResponse&);
    
    FHttpRequestPtr VPCCreateConsent(const VPCCreateConsentRequest& Request, const FVPCCreateConsentDelegate& Delegate = FVPCCreateConsentDelegate()) const;
    FHttpRequestPtr VPCGetConsent(const VPCGetConsentRequest& Request, const FVPCGetConsentDelegate& Delegate = FVPCGetConsentDelegate()) const;
    FHttpRequestPtr VPCGetConsentZero(const VPCGetConsentZeroRequest& Request, const FVPCGetConsentZeroDelegate& Delegate = FVPCGetConsentZeroDelegate()) const;
    
private:
    void OnVPCCreateConsentResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FVPCCreateConsentDelegate Delegate) const;
    void OnVPCGetConsentResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FVPCGetConsentDelegate Delegate) const;
    void OnVPCGetConsentZeroResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FVPCGetConsentZeroDelegate Delegate) const;
    
	FHttpRequestRef CreateHttpRequest(const Request& Request) const;
	bool IsValid() const;
	void HandleResponse(FHttpResponsePtr HttpResponse, bool bSucceeded, Response& InOutResponse) const;

	FString Url;
	TMap<FString,FString> AdditionalHeaderParams;
	mutable FHttpRetrySystem::FManager* RetryManager = nullptr;
	mutable TUniquePtr<HttpRetryManager> DefaultRetryManager;
};

}
