/**
 * prodapi.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIVPRApi.h"

#include "OpenAPIGooglerpcStatus.h"
#include "OpenAPIVpcAgeCheckReceipt.h"
#include "OpenAPIVpcVPRRequestZero.h"

namespace OpenAPI
{

/* 

*/
class OPENAPI_API OpenAPIVPRApi::VPRGetVPRRequest : public Request
{
public:
    virtual ~VPRGetVPRRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	TOptional<FString> Contact;
	TOptional<FString> Dob;
	TOptional<FString> Name;
};

class OPENAPI_API OpenAPIVPRApi::VPRGetVPRResponse : public Response
{
public:
    virtual ~VPRGetVPRResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIVpcAgeCheckReceipt Content;
};

/* 

*/
class OPENAPI_API OpenAPIVPRApi::VPRGetVPRZeroRequest : public Request
{
public:
    virtual ~VPRGetVPRZeroRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	OpenAPIVpcVPRRequestZero Body;
};

class OPENAPI_API OpenAPIVPRApi::VPRGetVPRZeroResponse : public Response
{
public:
    virtual ~VPRGetVPRZeroResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIVpcAgeCheckReceipt Content;
};

}
