/**
 * prodapi.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIProtobufAny.h"

namespace OpenAPI
{

/*
 * OpenAPIGooglerpcStatus
 *
 * 
 */
class OPENAPI_API OpenAPIGooglerpcStatus : public Model
{
public:
    virtual ~OpenAPIGooglerpcStatus() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<int32> Code;
	TOptional<FString> Message;
	TOptional<TArray<OpenAPIProtobufAny>> Details;
};

}
