/**
 * prodapi.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace OpenAPI
{

/*
 * OpenAPIVpcSelfAgeEligibilityRequest
 *
 * 
 */
class OPENAPI_API OpenAPIVpcSelfAgeEligibilityRequest : public Model
{
public:
    virtual ~OpenAPIVpcSelfAgeEligibilityRequest() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<FString> Token;
	TOptional<FString> Contact;
	TOptional<FString> Dob;
	/* Inclusive. Defaults to 0. */
	TOptional<int32> MinAge;
	/* Inclusive. Defaults to 2^31-1. */
	TOptional<int32> MaxAge;
};

}
