/**
 * prodapi.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPISelfServiceApi.h"

#include "OpenAPIGooglerpcStatus.h"
#include "OpenAPIVpcSelfAgeEligibilityRequest.h"
#include "OpenAPIVpcSelfAgeEligibilityResponse.h"
#include "OpenAPIVpcSelfConsentRequest.h"
#include "OpenAPIVpcSelfVerificationRequest.h"
#include "OpenAPIVpcSelfVerificationResponse.h"

namespace OpenAPI
{

/* 

*/
class OPENAPI_API OpenAPISelfServiceApi::SelfServiceCheckAgeEligibilityRequest : public Request
{
public:
    virtual ~SelfServiceCheckAgeEligibilityRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	OpenAPIVpcSelfAgeEligibilityRequest Body;
};

class OPENAPI_API OpenAPISelfServiceApi::SelfServiceCheckAgeEligibilityResponse : public Response
{
public:
    virtual ~SelfServiceCheckAgeEligibilityResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIVpcSelfAgeEligibilityResponse Content;
};

/* 

*/
class OPENAPI_API OpenAPISelfServiceApi::SelfServiceConsentRequest : public Request
{
public:
    virtual ~SelfServiceConsentRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	OpenAPIVpcSelfConsentRequest Body;
};

class OPENAPI_API OpenAPISelfServiceApi::SelfServiceConsentResponse : public Response
{
public:
    virtual ~SelfServiceConsentResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    TSharedPtr<FJsonObject> Content;
};

/* 

*/
class OPENAPI_API OpenAPISelfServiceApi::SelfServiceVerifyRequest : public Request
{
public:
    virtual ~SelfServiceVerifyRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	OpenAPIVpcSelfVerificationRequest Body;
};

class OPENAPI_API OpenAPISelfServiceApi::SelfServiceVerifyResponse : public Response
{
public:
    virtual ~SelfServiceVerifyResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIVpcSelfVerificationResponse Content;
};

}
