/**
 * prodapi.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIVpcConsent.h"
#include "OpenAPIVpcIdentity.h"

namespace OpenAPI
{

/*
 * OpenAPIVpcSelfConsentRequest
 *
 * 
 */
class OPENAPI_API OpenAPIVpcSelfConsentRequest : public Model
{
public:
    virtual ~OpenAPIVpcSelfConsentRequest() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<FString> Token;
	TOptional<OpenAPIVpcIdentity> Identity;
	TOptional<OpenAPIVpcConsent> Consent;
	TOptional<FString> CustomId;
};

}
