/**
 * prodapi.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIVeripassG1Claim.h"

namespace OpenAPI
{

/*
 * OpenAPIVpcConsentRequestZero
 *
 * 
 */
class OPENAPI_API OpenAPIVpcConsentRequestZero : public Model
{
public:
    virtual ~OpenAPIVpcConsentRequestZero() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<OpenAPIVeripassG1Claim> Claim;
	TOptional<TArray<FString>> Subject;
	TOptional<int32> Ttl;
	TOptional<FString> NotifyContact;
	TOptional<FString> NotifyVisitUrl;
	TOptional<FString> CallbackUrl;
	TOptional<FString> InfoUrl;
	TOptional<FString> CustomId;
};

}
