/**
 * prodapi.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIAuthApi.h"

#include "OpenAPIGooglerpcStatus.h"
#include "OpenAPIVpcAuthInfo.h"
#include "OpenAPIVpcAuthRequest.h"
#include "OpenAPIVpcAuthResponse.h"

namespace OpenAPI
{

/* 

*/
class OPENAPI_API OpenAPIAuthApi::AuthAuthRequest : public Request
{
public:
    virtual ~AuthAuthRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	OpenAPIVpcAuthRequest Body;
};

class OPENAPI_API OpenAPIAuthApi::AuthAuthResponse : public Response
{
public:
    virtual ~AuthAuthResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIVpcAuthResponse Content;
};

/* 

*/
class OPENAPI_API OpenAPIAuthApi::AuthValidateAuthRequest : public Request
{
public:
    virtual ~AuthValidateAuthRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

};

class OPENAPI_API OpenAPIAuthApi::AuthValidateAuthResponse : public Response
{
public:
    virtual ~AuthValidateAuthResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIVpcAuthInfo Content;
};

}
