/**
 * prodapi.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace OpenAPI
{

/*
 * OpenAPIVpcConsentRequest
 *
 * 
 */
class OPENAPI_API OpenAPIVpcConsentRequest : public Model
{
public:
    virtual ~OpenAPIVpcConsentRequest() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<FString> Contact;
	TOptional<int32> Ttl;
	TOptional<FString> Dob;
	TOptional<TArray<FString>> Subject;
	TOptional<FString> Name;
	TOptional<FString> VisitUrl;
	TOptional<FString> CallbackUrl;
	TOptional<FString> InfoUrl;
	TOptional<FString> CustomId;
	TOptional<FString> CustomerId;
};

}
