/**
 * prodapi.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIVpcConsentRequest.h"

#include "OpenAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

void OpenAPIVpcConsentRequest::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (Contact.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("contact")); WriteJsonValue(Writer, Contact.GetValue());
	}
	if (Ttl.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("ttl")); WriteJsonValue(Writer, Ttl.GetValue());
	}
	if (Dob.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("dob")); WriteJsonValue(Writer, Dob.GetValue());
	}
	if (Subject.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("subject")); WriteJsonValue(Writer, Subject.GetValue());
	}
	if (Name.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("name")); WriteJsonValue(Writer, Name.GetValue());
	}
	if (VisitUrl.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("visitUrl")); WriteJsonValue(Writer, VisitUrl.GetValue());
	}
	if (CallbackUrl.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("callbackUrl")); WriteJsonValue(Writer, CallbackUrl.GetValue());
	}
	if (InfoUrl.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("infoUrl")); WriteJsonValue(Writer, InfoUrl.GetValue());
	}
	if (CustomId.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("customId")); WriteJsonValue(Writer, CustomId.GetValue());
	}
	if (CustomerId.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("customerId")); WriteJsonValue(Writer, CustomerId.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool OpenAPIVpcConsentRequest::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("contact"), Contact);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("ttl"), Ttl);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("dob"), Dob);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("subject"), Subject);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("name"), Name);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("visitUrl"), VisitUrl);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("callbackUrl"), CallbackUrl);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("infoUrl"), InfoUrl);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("customId"), CustomId);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("customerId"), CustomerId);

	return ParseSuccess;
}

}
