/**
 * prodapi.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIVeripassConsentReceiptStatus.h"

#include "OpenAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

inline FString ToString(const OpenAPIVeripassConsentReceiptStatus::Values& Value)
{
	switch (Value)
	{
	case OpenAPIVeripassConsentReceiptStatus::Values::Unknown:
		return TEXT("UNKNOWN");
	case OpenAPIVeripassConsentReceiptStatus::Values::Pending:
		return TEXT("PENDING");
	case OpenAPIVeripassConsentReceiptStatus::Values::Approved:
		return TEXT("APPROVED");
	case OpenAPIVeripassConsentReceiptStatus::Values::Rejected:
		return TEXT("REJECTED");
	}

	UE_LOG(LogOpenAPI, Error, TEXT("Invalid OpenAPIVeripassConsentReceiptStatus::Values Value (%d)"), (int)Value);
	return TEXT("");
}

FString OpenAPIVeripassConsentReceiptStatus::EnumToString(const OpenAPIVeripassConsentReceiptStatus::Values& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, OpenAPIVeripassConsentReceiptStatus::Values& Value)
{
	static TMap<FString, OpenAPIVeripassConsentReceiptStatus::Values> StringToEnum = { 
		{ TEXT("UNKNOWN"), OpenAPIVeripassConsentReceiptStatus::Values::Unknown },
		{ TEXT("PENDING"), OpenAPIVeripassConsentReceiptStatus::Values::Pending },
		{ TEXT("APPROVED"), OpenAPIVeripassConsentReceiptStatus::Values::Approved },
		{ TEXT("REJECTED"), OpenAPIVeripassConsentReceiptStatus::Values::Rejected }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool OpenAPIVeripassConsentReceiptStatus::EnumFromString(const FString& EnumAsString, OpenAPIVeripassConsentReceiptStatus::Values& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline FStringFormatArg ToStringFormatArg(const OpenAPIVeripassConsentReceiptStatus::Values& Value)
{
	return FStringFormatArg(ToString(Value));
}

inline void WriteJsonValue(JsonWriter& Writer, const OpenAPIVeripassConsentReceiptStatus::Values& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, OpenAPIVeripassConsentReceiptStatus::Values& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

void OpenAPIVeripassConsentReceiptStatus::WriteJson(JsonWriter& Writer) const
{
	WriteJsonValue(Writer, Value);
}

bool OpenAPIVeripassConsentReceiptStatus::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	return TryGetJsonValue(JsonValue, Value);
}

}
