/**
 * prodapi.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIVpcSelfVerificationResponse.h"

#include "OpenAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

void OpenAPIVpcSelfVerificationResponse::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (ActivationRequired.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("activationRequired")); WriteJsonValue(Writer, ActivationRequired.GetValue());
	}
	if (ActivationFailed.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("activationFailed")); WriteJsonValue(Writer, ActivationFailed.GetValue());
	}
	if (Token.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("token")); WriteJsonValue(Writer, Token.GetValue());
	}
	if (Uid.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("uid")); WriteJsonValue(Writer, Uid.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool OpenAPIVpcSelfVerificationResponse::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("activationRequired"), ActivationRequired);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("activationFailed"), ActivationFailed);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("token"), Token);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("uid"), Uid);

	return ParseSuccess;
}

}
