/**
 * prodapi.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIVpcSelfAgeEligibilityRequest.h"

#include "OpenAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

void OpenAPIVpcSelfAgeEligibilityRequest::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (Token.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("token")); WriteJsonValue(Writer, Token.GetValue());
	}
	if (Contact.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("contact")); WriteJsonValue(Writer, Contact.GetValue());
	}
	if (Dob.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("dob")); WriteJsonValue(Writer, Dob.GetValue());
	}
	if (MinAge.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("minAge")); WriteJsonValue(Writer, MinAge.GetValue());
	}
	if (MaxAge.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("maxAge")); WriteJsonValue(Writer, MaxAge.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool OpenAPIVpcSelfAgeEligibilityRequest::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("token"), Token);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("contact"), Contact);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("dob"), Dob);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("minAge"), MinAge);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("maxAge"), MaxAge);

	return ParseSuccess;
}

}
