/**
 * prodapi.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIVeripassG1HashSet.h"

#include "OpenAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

void OpenAPIVeripassG1HashSet::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (Hashes.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("hashes")); WriteJsonValue(Writer, Hashes.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool OpenAPIVeripassG1HashSet::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("hashes"), Hashes);

	return ParseSuccess;
}

}
