/**
 * prodapi.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIVpcSelfConsentRequest.h"

#include "OpenAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

void OpenAPIVpcSelfConsentRequest::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (Token.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("token")); WriteJsonValue(Writer, Token.GetValue());
	}
	if (Identity.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("identity")); WriteJsonValue(Writer, Identity.GetValue());
	}
	if (Consent.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("consent")); WriteJsonValue(Writer, Consent.GetValue());
	}
	if (CustomId.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("customId")); WriteJsonValue(Writer, CustomId.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool OpenAPIVpcSelfConsentRequest::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("token"), Token);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("identity"), Identity);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("consent"), Consent);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("customId"), CustomId);

	return ParseSuccess;
}

}
