/**
 * prodapi.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIVeripassG1Claim.h"

#include "OpenAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

void OpenAPIVeripassG1Claim::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (Anchors.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("anchors")); WriteJsonValue(Writer, Anchors.GetValue());
	}
	if (Age.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("age")); WriteJsonValue(Writer, Age.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool OpenAPIVeripassG1Claim::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("anchors"), Anchors);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("age"), Age);

	return ParseSuccess;
}

}
